// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteObject(arg1:string,arg2:number):Promise<void>;

export function GetDevices():Promise<Array<main.DeviceOutput>>;

export function GetObjects(arg1:string,arg2:number,arg3:number):Promise<Array<main.ObjectOutput>>;

export function GetStorages(arg1:string):Promise<Array<main.StorageOutput>>;

export function PutObjects(arg1:string,arg2:number,arg3:number,arg4:Array<string>):Promise<void>;

export function RenameObject(arg1:string,arg2:number,arg3:string):Promise<void>;
