// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteObject(arg1, arg2) {
  return window['go']['main']['App']['DeleteObject'](arg1, arg2);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetObjects(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetObjects'](arg1, arg2, arg3);
}

export function GetStorages(arg1) {
  return window['go']['main']['App']['GetStorages'](arg1);
}

export function RenameObject(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameObject'](arg1, arg2, arg3);
}
